namespace App.Interfaces.Util {

    export interface IDataGridScope extends ng.IScope{
        fieldList: any,
        columnList: any,
        grouping: any,
        filtering: any,
        selectionMode: any,
        selectionChanged: any,
        multipleSelect: any,
        autoExpand: any,
        pageSize: any,
        editing: any,
        rowUpdated: any,
        exportEnabled: any,
        exportFileName: any,
        rowClick: any,
        rowPrepared: any,
        insert: any,
        remove: any,
        pagerEnabled: any,
        pageSizeSelectorEnabled: any,
        selectedRowKeys: any,
        showExportBtn: any,
        dragAndDropFunction: any,
        wordWrapEnabled: any,
        hideTotal: any,
        onRowInserting: any,
        onRowUpdating: any,
        editMode: any,
        gridId: any,
        isCustomStore: any,
        totalCount: any,
        summary: any,
        columnFixing: any,
        applyFilter: any,
        onExportedFunction: any,
    }

}